import { mkdtemp, readFile, rm } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { afterEach, describe, expect, it, vi } from "vitest";
import { deriveFscStockQuotes } from "../../../scripts/derive-fsc-stock-quotes.mjs";
import { retrieveFscStockQuotes } from "../../../scripts/retrieve-fsc-stock-quotes.mjs";
import {
  parseJsonLinesSourceArtifact,
  sourceArtifactHash,
} from "./source-ingest";

// Synthetic values only. This is not captured publisher output.
const window = { basDt: "20240229", market: "KOSPI" };
const items = ["A", "B"].map((id) => ({
  basDt: window.basDt,
  srtnCd: `SYNTH-${id}`,
  isinCd: `SYNTH-INSTRUMENT-${id}`,
  mrktCtg: window.market,
  clpr: "90071992547409931234567890.00100",
  trqu: "0001.0",
  note: '합성, "문자"\n다음 줄',
  empty: "",
}));
function envelope(value: unknown = items) {
  return {
    response: {
      header: { resultCode: "00", resultMsg: "NORMAL SERVICE." },
      body: { pageNo: 1, numOfRows: 40, totalCount: 2, items: { item: value } },
    },
  };
}
const encode = (value: unknown) =>
  Buffer.from(JSON.stringify(value, null, 2) + "\n\n");
const directories: string[] = [];
afterEach(async () => {
  vi.unstubAllEnvs();
  vi.restoreAllMocks();
  await Promise.all(
    directories
      .splice(0)
      .map((path) => rm(path, { recursive: true, force: true })),
  );
});

describe("offline response derivation with synthetic envelopes", () => {
  it("reproduces full rows, ordered columns and exact JSONL/generated bytes through the existing parser", () => {
    const bytes = encode(envelope());
    const first = deriveFscStockQuotes(bytes, window);
    const second = deriveFscStockQuotes(bytes, window);
    expect(first).toEqual(second);
    expect(first.jsonl).toBe(
      items.map((item) => JSON.stringify(item)).join("\n") + "\n",
    );
    expect(first.rows.map(({ values }) => values)).toEqual(items);
    expect(first.rows.map(({ values }) => Object.keys(values))).toEqual(
      items.map(Object.keys),
    );
    expect(first.generatedRows).toBe(
      JSON.stringify(first.rows, null, 2) + "\n",
    );
    expect(first.rows).toEqual(
      parseJsonLinesSourceArtifact(
        Buffer.from(first.jsonl),
        first.sourceArtifactHash,
      ),
    );
    expect(first.rows.map(({ coordinate }) => coordinate.rowNumber)).toEqual([
      "1",
      "2",
    ]);
    expect(first.rawResponseHash).toBe(sourceArtifactHash(bytes));
    expect(first.generatedRowsHash).toBe(
      sourceArtifactHash(Buffer.from(first.generatedRows)),
    );
    expect(first.rawResponseHash).not.toBe(first.sourceArtifactHash);
  });

  it.each([
    null,
    {},
    [],
    envelope([]),
    envelope([items[0]]),
    envelope(Array(41).fill(items[0])),
    envelope([items[0], { ...items[1], trqu: 123 }]),
    envelope([items[0], { ...items[1], clpr: null }]),
    envelope([items[0], { ...items[1], extra: {} }]),
    envelope([items[0], { ...items[1], basDt: "20240301" }]),
    envelope([items[0], { ...items[1], mrktCtg: "KOSDAQ" }]),
    envelope([items[0], { ...items[1], srtnCd: items[0]!.srtnCd }]),
    envelope([items[0], { ...items[1], isinCd: items[0]!.isinCd }]),
    envelope([items[0], { ...items[1], srtnCd: " " }]),
    envelope([items[0], { ...items[1], isinCd: "" }]),
  ])(
    "fails closed on malformed envelopes and invalid complete windows",
    (input) => {
      expect(() => deriveFscStockQuotes(encode(input), window)).toThrow();
    },
  );

  it("rejects provider errors separately from the shape and requires honest pagination", () => {
    const failed = envelope();
    failed.response.header.resultCode = "30";
    expect(() => deriveFscStockQuotes(encode(failed), window)).toThrow(
      "not successful",
    );
    const incomplete = envelope();
    incomplete.response.body.totalCount = 100;
    expect(() => deriveFscStockQuotes(encode(incomplete), window)).toThrow(
      "pagination",
    );
    expect(() => deriveFscStockQuotes(Buffer.from([0xff]), window)).toThrow(
      "UTF-8",
    );
  });
});

describe("manual acquisition boundaries with mocked transport", () => {
  async function options() {
    const directory = await mkdtemp(
      join(tmpdir(), "weavetrail-acquisition-test-"),
    );
    directories.push(directory);
    return {
      ...window,
      output: join(directory, "response.json"),
      permissionCheckedAt: new Date().toISOString().slice(0, 10),
    };
  }

  it("requires a key and same-day licence verification before any request", async () => {
    const request = vi.fn();
    vi.stubEnv("DATA_GO_KR_SERVICE_KEY", "");
    const input = await options();
    await expect(retrieveFscStockQuotes(input, request)).rejects.toThrow(
      "not configured",
    );
    vi.stubEnv("DATA_GO_KR_SERVICE_KEY", "synthetic-test-key");
    await expect(
      retrieveFscStockQuotes(
        { ...input, permissionCheckedAt: "2000-01-01" },
        request,
      ),
    ).rejects.toThrow("Recheck");
    expect(request).not.toHaveBeenCalled();
  });

  it.each(["synthetic+test/key=", "synthetic%2Btest%2Fkey%3D"])(
    "encodes the synthetic key once and preserves the entity bytes without overwrite (%s)",
    async (key) => {
      vi.stubEnv("DATA_GO_KR_SERVICE_KEY", key);
      const input = await options();
      const bytes = encode(envelope());
      const request = vi.fn(async (url: URL | RequestInfo) => {
        const parsed = new URL(String(url));
        expect(parsed.searchParams.get("serviceKey")).toBe(
          "synthetic+test/key=",
        );
        expect(
          Object.fromEntries(
            [...parsed.searchParams].filter(([name]) => name !== "serviceKey"),
          ),
        ).toEqual({
          basDt: window.basDt,
          resultType: "json",
          pageNo: "1",
          numOfRows: "40",
          mrktCls: window.market,
        });
        return new Response(bytes, {
          headers: { "content-type": "application/json" },
        });
      });
      await retrieveFscStockQuotes(input, request);
      expect(await readFile(input.output)).toEqual(bytes);
      const receipt = await readFile(`${input.output}.receipt.json`, "utf8");
      expect(JSON.parse(receipt).parameters.serviceKey).toBe("REDACTED");
      expect(receipt).not.toContain("synthetic+test");
      await expect(retrieveFscStockQuotes(input, request)).rejects.toThrow();
      expect(await readFile(input.output)).toEqual(bytes);
    },
  );

  it("sanitizes transport failures and refuses HTTP errors, provider errors and echoed credentials", async () => {
    vi.stubEnv("DATA_GO_KR_SERVICE_KEY", "synthetic-private-key");
    const input = await options();
    await expect(
      retrieveFscStockQuotes(input, async () => {
        throw new Error(
          "https://example.invalid?serviceKey=synthetic-private-key",
        );
      }),
    ).rejects.toThrow("Retrieval failed at the HTTP or transport boundary");
    await expect(
      retrieveFscStockQuotes(
        input,
        async () => new Response("", { status: 503 }),
      ),
    ).rejects.toThrow("HTTP or transport");
    const failed = envelope();
    failed.response.header.resultCode = "30";
    await expect(
      retrieveFscStockQuotes(input, async () => new Response(encode(failed))),
    ).rejects.toThrow("not successful");
    await expect(
      retrieveFscStockQuotes(
        input,
        async () => new Response("synthetic-private-key"),
      ),
    ).rejects.toThrow("echoes credentials");
    await expect(readFile(input.output)).rejects.toThrow();
  });
});
