import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import {
  requiresMappingOverride,
  type ApprovalRecord,
} from "@weavetrail/contracts";
import {
  fscStockQuotesProposal,
  realMarketDataScenarios,
} from "@weavetrail/scenarios";
import { deriveFscStockQuotes } from "../../../scripts/derive-fsc-stock-quotes.mjs";
import {
  applyApprovedMapping,
  approvedSourceMapping,
  deriveEventId,
  deriveRawRowHash,
  parseJsonLinesSourceArtifact,
  sourceArtifactHash,
} from "./source-ingest";
import { mappingApprovalArtifact, replayApproved } from "./approval-validation";
import { computeDatasetProfile } from "./dataset-profile";
import { sha256Canonical } from "./canonical-hash";
import { RequestWorkflow } from "./request-workflow";

const scenario =
  realMarketDataScenarios["real/fsc-stock-quotes-20260903.jsonl"];
const proposal = fscStockQuotesProposal;
const approval: ApprovalRecord = {
  approvedArtifactHash: sha256Canonical(mappingApprovalArtifact(proposal)),
  reviewerRef: "normalization-test-reviewer",
  decision: "APPROVED",
  approvedAt: "2026-09-05T19:31:27.527Z",
  overrides: proposal.fields.flatMap((field, index) =>
    requiresMappingOverride(field)
      ? [
          {
            fieldPath: `fields.${index}`,
            reason: `Accept ${field.sourceColumn} only as the documented daily-quote interpretation: ${field.evidence}`,
          },
        ]
      : [],
  ),
};
const read = (path: string) =>
  readFileSync(new URL(`../../scenarios/src/${path}`, import.meta.url));

describe("committed FSC daily quotation artifact", () => {
  it("pins raw, runtime and generated bytes and reproduces all generated bytes offline", () => {
    const raw = read("sources/real/fsc-stock-quotes-20260903.response.json");
    const jsonl = read("sources/real/fsc-stock-quotes-20260903.jsonl");
    const generated = read("generated/fsc-stock-quotes-20260903-rows.json");
    expect(sourceArtifactHash(raw)).toBe(
      "4ad9c1e1677a19b4fd28b766ae32883d82ec824b66a2687f1533198f18cc5b43",
    );
    expect(sourceArtifactHash(jsonl)).toBe(
      "17d3e9462f2322b0227554d76a4c7c4022261b4976727b3884f452d68f075eea",
    );
    expect(sourceArtifactHash(generated)).toBe(
      "b22afd23826096720fa1251bb3ee8908047bc3d4544075d21ae9fbc6d3809b8c",
    );
    const result = deriveFscStockQuotes(raw, {
      basDt: "20260903",
      market: "KOSPI",
    });
    expect(Buffer.from(result.jsonl)).toEqual(jsonl);
    expect(Buffer.from(result.generatedRows)).toEqual(generated);
    expect(result.rows).toEqual(scenario.rows);
    expect(scenario.rows).toEqual(
      parseJsonLinesSourceArtifact(jsonl, scenario.sourceArtifactHash),
    );
    const provenance = scenario.provenance;
    expect(provenance.artifacts.rawResponse.sha256).toBe(
      result.rawResponseHash,
    );
    expect(provenance.artifacts.runtimeJsonl.sha256).toBe(
      result.sourceArtifactHash,
    );
    expect(provenance.artifacts.generatedRows.sha256).toBe(
      result.generatedRowsHash,
    );
  });

  it("retains the complete first published page, every column/value and honest one-day issue identities", () => {
    const items = JSON.parse(
      read("sources/real/fsc-stock-quotes-20260903.response.json").toString(),
    ).response.body.items.item as Record<string, string>[];
    expect(items).toHaveLength(40);
    expect(scenario.rows.map(({ values }) => values)).toEqual(items);
    expect(scenario.rows.map(({ values }) => Object.keys(values))).toEqual(
      items.map(Object.keys),
    );
    expect(new Set(items.map(({ basDt }) => basDt))).toEqual(
      new Set(["20260903"]),
    );
    expect(new Set(items.map(({ mrktCtg }) => mrktCtg))).toEqual(
      new Set(["KOSPI"]),
    );
    for (const field of ["srtnCd", "isinCd"]) {
      expect(items.every((item) => item[field]!.length > 0)).toBe(true);
      expect(new Set(items.map((item) => item[field])).size).toBe(40);
    }
    expect(scenario.rows.map(({ coordinate }) => coordinate.rowNumber)).toEqual(
      Array.from({ length: 40 }, (_, index) => String(index + 1)),
    );
    expect(scenario.columns).toEqual(scenario.provenance.derivation.columns);
    expect(scenario.provenance.pagination).toEqual({
      pageNo: 1,
      numOfRows: 40,
      totalCount: 943,
    });
    expect(scenario.rows[0]!.values.fltRt).toBe(".78");
    expect(scenario).not.toHaveProperty("manifest");
    expect(scenario).not.toHaveProperty("expectedResult");
    expect(scenario).not.toHaveProperty("mappingApproval");
  });

  it("requires exactly the date, closing price and aggregate volume overrides and preserves all absent dimensions", () => {
    expect(
      proposal.fields
        .filter(requiresMappingOverride)
        .map(({ sourceColumn, confidence, status }) => ({
          sourceColumn,
          confidence,
          status,
        })),
    ).toEqual(
      ["basDt", "clpr", "trqu"].map((sourceColumn) => ({
        sourceColumn,
        confidence: 0,
        status: "REVIEW_REQUIRED",
      })),
    );
    for (const supplied of [
      undefined,
      { ...approval, overrides: [] },
      {
        ...approval,
        overrides: approval.overrides.map((override) => ({
          ...override,
          reason: " ",
        })),
      },
    ]) {
      const workflow = new RequestWorkflow();
      const result = replayApproved(
        scenario.rows,
        scenario.rows,
        proposal,
        supplied,
        undefined,
        "baseline",
        workflow,
      );
      expect(workflow.state).toBe("MAPPING_REVIEW_REQUIRED");
      expect(result).not.toHaveProperty("canonicalResultHash");
    }
    const normalized = applyApprovedMapping(
      scenario.rows,
      approvedSourceMapping(proposal),
    );
    if (normalized.status !== "APPROVED")
      throw new Error("Expected daily normalization");
    expect(normalized.events).toHaveLength(40);
    normalized.events.forEach((event, index) => {
      const row = scenario.rows[index]!;
      expect(event).toEqual({
        schemaVersion: "1.2",
        eventType: "DAILY_QUOTE",
        datasetId: "fsc-stock-quotes-20260903-v1",
        venueId: "KRX-KOSPI",
        sourceEventId: row.values.srtnCd,
        instrumentId: row.values.isinCd,
        eventTime: "2026-09-03T00:00:00+09:00",
        price: row.values.clpr,
        quantity: row.values.trqu,
        eventId: deriveEventId({
          ...proposal.constants,
          sourceEventId: row.values.srtnCd,
        }),
        rawRowHash: deriveRawRowHash(row),
      });
      for (const field of [
        "side",
        "actorId",
        "counterpartyId",
        "orderId",
        "sequence",
        "receivedAt",
      ])
        expect(Object.hasOwn(event, field)).toBe(false);
    });
    expect(computeDatasetProfile(normalized.events).actorIds).toEqual([]);
  });

  it("pins actual foundation/dataset goldens with repeat, shuffle and derived duplicate invariance", () => {
    const runs = (
      ["baseline", "baseline", "shuffle", "duplicate"] as const
    ).map((mutation) => {
      const workflow = new RequestWorkflow();
      const result = replayApproved(
        mutation === "shuffle" ? [...scenario.rows].reverse() : scenario.rows,
        scenario.rows,
        proposal,
        approval,
        undefined,
        mutation,
        workflow,
      );
      expect(workflow.state).toBe("MAPPING_APPROVED");
      if (!("canonicalResultHash" in result))
        throw new Error("Expected foundation normalization");
      expect(result).not.toHaveProperty("evaluation");
      expect(result).not.toHaveProperty("sourceTrace");
      return result;
    });
    expect(
      new Set(runs.map(({ canonicalResultHash }) => canonicalResultHash)).size,
    ).toBe(1);
    expect(
      new Set(
        runs.map(
          ({ events }) => computeDatasetProfile(events).canonicalDatasetHash,
        ),
      ).size,
    ).toBe(1);
    expect(runs.map(({ duplicateCount }) => duplicateCount)).toEqual([
      0, 0, 0, 1,
    ]);
    expect(runs.map(({ canonicalEventCount }) => canonicalEventCount)).toEqual([
      40, 40, 40, 40,
    ]);
    expect(
      runs[0]!.events.every(
        ({ eventTime }) => eventTime === "2026-09-02T15:00:00.000000000Z",
      ),
    ).toBe(true);
    expect({
      foundationHash: runs[0]!.canonicalResultHash,
      datasetHash: computeDatasetProfile(runs[0]!.events).canonicalDatasetHash,
      mappingApprovalHash: approval.approvedArtifactHash,
    }).toMatchInlineSnapshot(`
      {
        "datasetHash": "2f70f316b6a7979b2472e2ebfc0da303c69961ed0833e060762e1567d39af939",
        "foundationHash": "f8bb2a21d695aab89e826039861204ecb741d5f56ecab69e354c9b5840ae25fc",
        "mappingApprovalHash": "ff68d2191610b9f63800b33e25d4eec8d2535090d2625fff51c4b9b2e1aff2cc",
      }
    `);
  });

  it("keeps display provenance outside approval and canonical hashes", () => {
    const changedDisplay = {
      ...scenario,
      provenance: {
        ...scenario.provenance,
        retrievedAt: "2030-01-01T00:00:00Z",
        titleEnglish: "Updated display title",
      },
    };
    const run = (source: typeof scenario) =>
      replayApproved(
        source.rows,
        source.rows,
        source.mappingProposal,
        approval,
        undefined,
      );
    expect(run(changedDisplay)).toEqual(run(scenario));
    expect(mappingApprovalArtifact(changedDisplay.mappingProposal)).toEqual(
      mappingApprovalArtifact(proposal),
    );
  });
});
