import type { TradeEvent } from "@weavetrail/contracts";

export const concentratedBuyEvents = [
  {
    schemaVersion: "1.0",
    eventId: "evt-003",
    sourceEventId: "source-003",
    datasetId: "synthetic-concentrated-buy-v1",
    venueId: "SYNTH-X",
    eventTime: "2026-08-25T00:00:02.000Z",
    receivedAt: "2026-08-25T00:00:02.080Z",
    sequence: "3",
    instrumentId: "WT-DEMO",
    eventType: "TRADE",
    side: "BUY",
    actorId: "actor-c",
    counterpartyId: "liquidity-3",
    orderId: "order-003",
    price: "101.25",
    quantity: "4.00",
    rawRowHash:
      "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc",
  },
  {
    schemaVersion: "1.0",
    eventId: "evt-001",
    sourceEventId: "source-001",
    datasetId: "synthetic-concentrated-buy-v1",
    venueId: "SYNTH-X",
    eventTime: "2026-08-25T00:00:00.000Z",
    receivedAt: "2026-08-25T00:00:00.040Z",
    sequence: "1",
    instrumentId: "WT-DEMO",
    eventType: "TRADE",
    side: "BUY",
    actorId: "actor-a",
    counterpartyId: "liquidity-1",
    orderId: "order-001",
    price: "100.00",
    quantity: "2.00",
    rawRowHash:
      "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
  },
  {
    schemaVersion: "1.0",
    eventId: "evt-004",
    sourceEventId: "source-004",
    datasetId: "synthetic-concentrated-buy-v1",
    venueId: "SYNTH-X",
    eventTime: "2026-08-25T00:00:02.000Z",
    receivedAt: "2026-08-25T00:00:02.110Z",
    sequence: "4",
    instrumentId: "WT-DEMO",
    eventType: "TRADE",
    side: "SELL",
    actorId: "actor-d",
    counterpartyId: "liquidity-4",
    orderId: "order-004",
    price: "101.20",
    quantity: "1.25",
    rawRowHash:
      "dddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddddd",
  },
  {
    schemaVersion: "1.0",
    eventId: "evt-002",
    sourceEventId: "source-002",
    datasetId: "synthetic-concentrated-buy-v1",
    venueId: "SYNTH-X",
    eventTime: "2026-08-25T00:00:01.000Z",
    receivedAt: "2026-08-25T00:00:01.050Z",
    sequence: "2",
    instrumentId: "WT-DEMO",
    eventType: "TRADE",
    side: "BUY",
    actorId: "actor-b",
    counterpartyId: "liquidity-2",
    orderId: "order-002",
    price: "100.80",
    quantity: "3.50",
    rawRowHash:
      "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb",
  },
] satisfies TradeEvent[];
